---
# TODO: Add alternative steps for centos, other distros.

- name: Install packages required for docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - linux-image-extra-virtual
    state: latest
  with_items:

- name: Install gpg key for ubuntu using local version.
  apt_key:
    data: "{{ lookup('file', 'docker.asc') }}"
    state: present


- name: Get os release name
  command: lsb_release -cs
  register: ubuntu_release

- name: Output ubuntu release
  debug:
    msg: "Ubuntu release version {{ ubuntu_release.stdout }}"

- name: Add repo for Docker CE
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_release.stdout }} stable"
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Create a docker group
  group:
    name: docker
    state: present

- name: Install docker community edition
  apt:
    name: "{{ hostvars[inventory_hostname].docker_lib | default(docker_lib) }}"
    state: present
  notify:
    - start docker

- name: Add "{{ ssh_user }}"  user to docker group
  user:
    name: "{{ ssh_user }}"
    append: yes
    groups: docker
